[default]
extend-ignore-identifiers-re = [
  # appear in several grammars
  "PN_[A-Z_]+",
  "pn_local",
  # I prefer this to 'type_'
  "typ",
  "iz",
]
extend-ignore-re = [
  "raison d'Ãªtre",
  "Tak, tak, tak! - da kommen sie",
  "SELECTed",
]

